### ISSUE TITLE
Javascript text translation

### ISSUE THREAD

**Issue by siggj** [jonnitto/Jonnitto.PhotoSwipe#2]
Hello, 
What do you suggest  to translate text in javascript like "Share", "Download image" without change the javascript file ? 
Great package btw :)

**Comment by jonnitto** [comment]
This is a very good point. I'll extend the package with this function

**Comment by jonnitto** [comment]
# Help wanted:

- #3 French translation

- #4 Italian translation

**Comment by jonnitto** [comment]
Here you go:
- [Version 0.2.0](https://github.com/jonnitto/Jonnitto.PhotoSwipe/releases/0.2.0)
- [Version 1.3.0](https://github.com/jonnitto/Jonnitto.PhotoSwipe/releases/tag/1.3.0)
